apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: kroxy-admin-deny
  namespace: kroxy
  labels:
    app.kubernetes.io/name: kroxy
    app.kubernetes.io/component: network-policy
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: kroxy
  policyTypes:
  - Ingress
  ingress:
  - ports:
    - protocol: TCP
      port: 80
    - protocol: TCP
      port: 443
