apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: kroxy
  namespace: kroxy
  labels:
    app.kubernetes.io/name: kroxy
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kroxy
